name: Update Submodule

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: update submodule
        run: |
          git submodule update --remote --merge
          git add .
          git commit -m "update submodule"
          git push
